export const IMAGES = {
  SHOWCASE: new URL('./message-showcase.png', import.meta.url).href,
  LOGO: new URL('./logo-dock.png', import.meta.url).href,
  LOGO_WHITE: new URL('./logo-white.png', import.meta.url).href,
  WORKSPACE: new URL('./workspace-img.png', import.meta.url).href,
  ABOUT_US: new URL('./about-us.png', import.meta.url).href,
  BACKGRUND_CONTENT: new URL('./intro-picture.png', import.meta.url).href,
  LOGO_ACCOUNT: new URL('./logo-account.png', import.meta.url).href,
  AVT_TEXT: new URL('./avt.jpg', import.meta.url).href,
  LOGOFOOTER: new URL('./footer-logo.png', import.meta.url).href,
  CLAP: new URL('./clap.png', import.meta.url).href,
  DOWN: new URL('./down.png', import.meta.url).href,
  LIKE: new URL('./like.png', import.meta.url).href,
  LAUGH: new URL('./laugh.png', import.meta.url).href,
  ANGRY: new URL('./angry.png', import.meta.url).href,
  CRY: new URL('./cry.png', import.meta.url).href,
  UA: new URL('./ua.png', import.meta.url).href,
};
