export const ICONS = {
  HAPPY: new URL('./happy.svg', import.meta.url).href,
  GUARD: new URL('./guard.svg', import.meta.url).href,
  TIME: new URL('./time.svg', import.meta.url).href,
  GOOGLE: new URL('./google.svg', import.meta.url).href,
  EYE: new URL('./eye.svg', import.meta.url).href,
  HOME: new URL('./home.svg', import.meta.url).href,
  MESSAGE: new URL('./messages.svg', import.meta.url).href,
  BELL: new URL('./bell.svg', import.meta.url).href,
  ARROW_UP_LIGHT: new URL('./arrow-up.svg', import.meta.url).href,
  ARROW_DOWN_LIGHT: new URL('./arrow-down-light.svg', import.meta.url).href,
  ARROW_DOWN_BOLD: new URL('./arrow-down-bold.svg', import.meta.url).href,
  HASH: new URL('./hash.svg', import.meta.url).href,
  PLUS: new URL('./plus.svg', import.meta.url).href,
  FACEBOOK: new URL('./facebook.svg', import.meta.url).href,
  FIGMA: new URL('./figma.svg', import.meta.url).href,
  LINKEDIN: new URL('./linkedin.svg', import.meta.url).href,
  TWITER: new URL('./twitter.svg', import.meta.url).href,
  ARROW_LEFT: new URL('./arrow-left.svg', import.meta.url).href,
  PAPER_CLIP: new URL('./paper-clip.svg', import.meta.url).href,
  REACTION: new URL('./reaction.svg', import.meta.url).href,
  PLANE: new URL('./plane.svg', import.meta.url).href,
  REPLY: new URL('./reply.svg', import.meta.url).href,
  TRASH: new URL('./trash.svg', import.meta.url).href,
  MEDIA_FILE: new URL('./media-file.svg', import.meta.url).href,
};
